### ISSUE TITLE
As a clumsy user, I want to undo and redo my commands

### ISSUE THREAD

**Issue by jon-chua** [AY1920S1-CS2103T-F13-2/main#29]
so that i can undo my mistakes

**Comment by fatclarence** [comment]
Might not implement this because we can revert commands for now by typing the reverse of the command we just typed. So technically, we still fulfil the user story for now. However, it is a good to have feature as it will make it slightly more convenient for the user to revert mistakes. Good to have feature, but not a must-have.

**Comment by seanlowjk** [comment]
To be implemented in v2.0
